### ISSUE TITLE
Clarify Readme.md

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/fester#102]
For me the use of the word "default" in the readme (and in the help) implies that if you like the default, then you don't need to specify. Instead, in this instance I think the better word might be "expected" or "most usual".

**Comment by emcaulay** [comment]
Also, I think the description of what the festerize script does is actually smaller than what the script does? Festerize uploads the CSV to the IIIF Fester Service, invokes the service and returns a CSV with a link to the new manifest? (or maybe it only does that sometimes (if the CSV contains a collection or a work?)

**Comment by markmatney** [comment]
It actually is the case though that wherever there is a "default" value, the user doesn't need to specify. At least it should be -- is there an example where this isn't true?

I agree that we could improve the description.

**Comment by ksclarke** [comment]
![Screenshot from 2020-05-01 15-48-06](https://user-images.githubusercontent.com/106238/80838146-5a1f2f00-8bc6-11ea-8ab8-75cefc74dd49.png)

Yes, I think the "default" stuff is working as expected (see screenshot), but also agree on the description.

**Comment by ksclarke** [comment]
Fwiw, I created a Jira ticket IIIF-749 to mirror this one. We can close both of these when the work is done.

**Comment by markmatney** [comment]
closed with https://github.com/UCLALibrary/fester/pull/115
